python -u main_nn5.py \
  --seasonal_patterns Weekly \
  --root_path ./datasets/nn5/ \
  --train_epochs 100 --patience 20 --batch_size 16 --num_workers 2 \
  --learning_rate 1e-3 --loss SMAPE --lradj COS --tmax 20 --eta_min 1e-8 \
  --d_model 128 --d_ff 256 --n_heads 16 --e_layers 3 --transformer_ff_inner 256 \
  --dropout 0.1 --in_dropout 0.1 --out_dropout 0.1 \
  --hsg_layers 2 --cross_scale_g 1 --g_gate 1 \
  --learned_hyperedge_weights 0 \
  --scale_patch_sizes "2 4 8" --scale_strides "2 4 8" \
  --multi 0 --revin_flag 1 \
  --optimizer Adam --weight_decay 0.0 --warmup_epochs 0 \
  --seed 42 --exp_tag NN5_Weekly
