python -u main_m1.py \
  --seasonal_patterns Monthly \
  --root_path ./datasets/m1/ \
  --train_epochs 200 --patience 40 --batch_size 16 --num_workers 2 \
  --learning_rate 1.2e-3 --loss SMAPE --lradj COS --tmax 20 --eta_min 1e-8 \
  --d_model 128 --d_ff 256 --n_heads 16 --e_layers 3 --transformer_ff_inner 256 \
  --dropout 0.0 --in_dropout 0.0 --out_dropout 0.0 \
  --sch_layers 2 --cross_scale_g 1 --g_gate 1 \
  --learned_hyperedge_weights 0 \
  --scale_patch_sizes "4 8 12" --scale_strides "4 8 12" \
  --multi 0 --revin_flag 1 \
  --optimizer AdamW --weight_decay 0.05 --warmup_epochs 20 \
  --seed 42 --exp_tag M1_Monthly
